/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  reactSidebar: [{ type: 'autogenerated', dirName: 'react' }],
  weeklySidebar: [{ type: 'autogenerated', dirName: 'weekly' }],
  vueSidebar: [{ type: 'autogenerated', dirName: 'vue' }],
  aboutSidebar: [{ type: 'autogenerated', dirName: 'about' }],
  productsSidebar: [{ type: 'autogenerated', dirName: 'products' }],
  appSidebar: [{ type: 'autogenerated', dirName: 'app' }],
  backendSidebar: [{ type: 'autogenerated', dirName: 'backend' }],
  designSidebar: [{ type: 'autogenerated', dirName: 'design' }],
  devopsSidebar: [{ type: 'autogenerated', dirName: 'devops' }],
  frontendSidebar: [{ type: 'autogenerated', dirName: 'frontend' }],
  leetcodeSidebar: [{ type: 'autogenerated', dirName: 'leetcode' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
